version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  nginx1:
    image: nginx
    environment:
      - "VIRTUAL_HOST=m"

  nginx2:
    image: nginx
    environment:
      - "VIRTUAL_HOST=m"

  nginx3:
    image: nginx
    environment:
      - "VIRTUAL_HOST=m"

  nginx4:
    image: nginx
    environment:
      - "VIRTUAL_HOST=m"
